### ISSUE TITLE
Consider refactoring components with strict methodological significance to `pacta.data.preparation` or `pacta.scenario.preparation`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/workflow.data.preparation#94]
**PROBABLY DON'T DO THIS PRIOR TO SUCCESSFUL DELIVERY OF PACTA COP CH 2024** 

Towards a world where `workflow`s handle file I/O and configuration and DevOps mainly
and `pacta.*` handles as much methodology as possible. Relates to https://github.com/RMI-PACTA/practices/issues/2

- [x] maybe refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/357 and #208)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L94-L98

- [x] refactor to `pacta.scenario.preparation` ~(done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/358 and #209)~ not going to do this until after a switch to pacta.scenario.data.preparation is made
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L131-L146

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/359 and #210)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L175-L186

- [x] refactor to `pacta.scenario.preparation` ~(done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/358 and #209)~ not going to do this until after a switch to pacta.scenario.data.preparation is made
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L196-L213

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/348)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L260-L270

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/360 and #211)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L291-L320

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/348 and https://github.com/RMI-PACTA/pacta.data.preparation/pull/353)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L350-L370

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/348 and https://github.com/RMI-PACTA/pacta.data.preparation/pull/353)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L375-L403

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/351)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L421-L441

- [x] refactor to `pacta.data.prepartion` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/352)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L453-L476

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/348)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L489-L496

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/361 and #213)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L502-L533

- [x] refactor to `pacta.data.preparation` (done in https://github.com/RMI-PACTA/pacta.data.preparation/pull/361 and #213)
https://github.com/RMI-PACTA/workflow.data.preparation/blob/5801f959827584014019d560cb17470a4352e0dd/run_pacta_data_preparation.R#L547-L563

[AB#10388](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10388)

**Comment by jdhoffa** [comment]
cc: @AlexAxthelm and @cjyetman this would get us closer to having "all methodology" in `pacta.*` and "all file I/O" in `workflow.*`

**Comment by cjyetman** [comment]
note that any of the code here referencing `masterdata*` is unlikely to get added to `pacta.data.preparation` since we're *very* close to not using/relying on the masterdata files at all anymore

**Comment by cjyetman** [comment]
all but the scenario stuff has been implemented, closing
(scenario stuff will defer until pacta.scenario.data.preparation is implemented)
